sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    - icnsutils
    - graphicsmagick

cache:
  directories:
  - node_modules
  - $HOME/.npm/_prebuilds
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn install

script: 
  - if [ $TRAVIS_COMMIT_MESSAGE == *"!build"* ]
  - then
    - echo 'Linux build' && echo -en 'travis_fold:start:script.linux\\r'
    - DEBUG=electron-builder yarn run package:linux
    - echo -en 'travis_fold:end:script.linux\\r'
    - echo 'Mac build' && echo -en 'travis_fold:start:script.mac\\r'
    - DEBUG=electron-builder yarn run package:mac
    - echo -en 'travis_fold:end:script.mac\\r'
    - echo 'Win build' && echo -en 'travis_fold:start:script.win\\r'
    - sudo dpkg --add-architecture i386
    - wget -nc https://dl.winehq.org/wine-builds/Release.key
    - sudo apt-key add Release.key
    - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
    - sudo apt-get update
    - sudo apt-get install -y --install-recommends winehq-devel
    - DEBUG=electron-builder yarn run package:win
    - echo -en 'travis_fold:end:script.win\\r'
    - ./nightly.sh
  - fi
  - echo 'Done!'
  
# Disable coveralls for now
after_script:
  - npm run coveralls

#deploy:
#  - provider: releases
#    api-key:
#      secure: <>
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
